runtime: python27
api_version: 1
threadsafe: true

handlers:

 - url: /.well-known
   static_dir: well-known

 - url: /micro-manager/login
   script: app.main.app

 - url: /micro-manager/logout
   script: app.main.app

 - url: /micro-manager(\/?)
   static_files: admin-client/build/index.html
   upload: admin-client/build/.*\.html$
   login: admin

 - url: /api/(.*)
   script: app.main.app

 - url: /static
   static_dir: client/build/static
   secure: always

 - url: /(.*)
   static_files: client/build/index.html
   upload: client/build/.*\.html$
   secure: always

skip_files:
- ^(node_modules/.*)
- ^(admin-client/node_modules/.*)
- ^(client/node_modules/.*)
- ^(tests/.*)